#!/bin/bash



for ((i=0;i<=5;i++)); do
    sshpass -p "a" ssh -tp 2${i}022 root@loc "modprobe rbd"
done




rbd create foo --size 100000 -m ceph-node1

sudo rbd map foo --pool rbd --name client.admin -m ceph-node1

sudo mkfs.ext4 -m0 /dev/rbd/rbd/foo

sudo mkdir /mnt/ceph-block-device
sudo mount /dev/rbd/rbd/foo /mnt/ceph-block-device



