#!/bin/bash
# Argument = -n nodeNumber | -r remoteNodeNumber | -s 



function usage {
cat << EOF
usage: $0 options

This script run the test1 or test2 over a machine.

OPTIONS:
   -h      Show this message
   -n      Node number for single install
   -s      Synchronize ssh keys
   -r      Setup remote node
   -f      Format node disk to xfs
   -v      Verbose
EOF
}


DIRNAME=$(dirname $0)

source ${DIRNAME}/ceph.cfg

source ${DIRNAME}/install.sh
source ${DIRNAME}/network.sh
source ${DIRNAME}/functions.sh



NODE_NUMBER=0
GROUP_INSTALL=true
QUIET=
FORMAT_DRIVE=false

while getopts “n:r:sqfh” OPTION
do
     case $OPTION in
         h)
             usage
             exit
             ;;
         r)
             push_to_single_node $OPTARG
             exit 0
             ;;
         s)
             sync_ssh_keys $CEPH_USERNAME $CEPH_PASSWORD $SSH_KEY_FILE
             exit
             ;;
         n)  
             NODE_NUMBER=$OPTARG
             GROUP_INSTALL=false
             ;;
         q)
             QUIET="-q"
             ;;
         q)
             FORMAT_DRIVE=true
             ;;
         ?)
             usage
             exit
             ;;
     esac
done


setup_single_node


[ "$NODE_NUMBER" -eq 0 ] && install_ceph_deploy_rpm

[ "$NODE_NUMBER" -eq 0 ] && $GROUP_INSTALL && push_to_nodes







