#!/bin/bash


DIRNAME=$(dirname $0)

source ${DIRNAME}/ceph.cfg

source ${DIRNAME}/network.sh
source ${DIRNAME}/functions.sh

source ${DIRNAME}/argparse.sh

# generate hosts and ssh config file entries for ceph admin and ceph nodes 

set_hostname ${NODES[${NODE_NUMBER}-name]}

for (( i=0; i<$NODE_COUNT; i++ )); do
    add_hosts_ssh_entry ${NODES[$i-ip]} ${NODES[$i-name]} $SSH_KEY_FILE $CEPH_USERNAME
done


#### generate a new user and update ssh keys ####

add_ceph_user $CEPH_USERNAME $CEPH_PASSWORD $SSH_KEY_FILE



# format_xfs_drive ${NODES[${NODE_NUMBER}-disk]} ${MOUNTPOINT} 


# install_ceph_rpm
# install_extra_rpm

# install_kernel_lt_rpm

function push_to_nodes {

    sshpass -h > /dev/null 2>&1  || rpm -Uvh ${DIRNAME}/extra-rpm/sshpass-1.05-1.el6.x86_64.rpm

    for  (( i=1; i<$NODE_COUNT; i++ )); do
        echo "######## installing node: $i (${NODES[$i-ip]}) #######"
        sleep 1
        sshpass -p "${NODES[$i-password]}" scp -o StrictHostKeyChecking=no -r ${DIRNAME} "${NODES[$i-username]}@${NODES[$i-ip]}:"
        sshpass -p "${NODES[$i-password]}" ssh -o StrictHostKeyChecking=no -t ${NODES[$i-username]}@${NODES[$i-ip]} "${DIRNAME}/ceph $i"
    done

    sync_ssh_keys $CEPH_USERNAME $CEPH_PASSWORD $SSH_KEY_FILE

    # ssh_dissable_iptables

    for  (( i=1; i<$NODE_COUNT; i++ )); do
        sshpass -p "${NODES[$i-password]}" ssh -o StrictHostKeyChecking=no -t ${NODES[$i-username]}@${NODES[$i-ip]} "reboot"
    done

    reboot

}





